name: SwiftLint

on:
  pull_request:
    paths:
      - '**.swift'

jobs:
  swiftlint:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging

